// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// InitializeSimulation
void InitializeSimulation(double r, int nloci, int nploidy, int ninit0, int ninit1, int distlocal, double scmajor, double sclocal, int ngen, double rec, int k);
RcppExport SEXP _IntrogressionRcpp_InitializeSimulation(SEXP rSEXP, SEXP nlociSEXP, SEXP nploidySEXP, SEXP ninit0SEXP, SEXP ninit1SEXP, SEXP distlocalSEXP, SEXP scmajorSEXP, SEXP sclocalSEXP, SEXP ngenSEXP, SEXP recSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nloci(nlociSEXP);
    Rcpp::traits::input_parameter< int >::type nploidy(nploidySEXP);
    Rcpp::traits::input_parameter< int >::type ninit0(ninit0SEXP);
    Rcpp::traits::input_parameter< int >::type ninit1(ninit1SEXP);
    Rcpp::traits::input_parameter< int >::type distlocal(distlocalSEXP);
    Rcpp::traits::input_parameter< double >::type scmajor(scmajorSEXP);
    Rcpp::traits::input_parameter< double >::type sclocal(sclocalSEXP);
    Rcpp::traits::input_parameter< int >::type ngen(ngenSEXP);
    Rcpp::traits::input_parameter< double >::type rec(recSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    InitializeSimulation(r, nloci, nploidy, ninit0, ninit1, distlocal, scmajor, sclocal, ngen, rec, k);
    return R_NilValue;
END_RCPP
}
// RunSimulation
void RunSimulation();
RcppExport SEXP _IntrogressionRcpp_RunSimulation() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    RunSimulation();
    return R_NilValue;
END_RCPP
}
// WriteOutputandCleanup
Rcpp::List WriteOutputandCleanup();
RcppExport SEXP _IntrogressionRcpp_WriteOutputandCleanup() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(WriteOutputandCleanup());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IntrogressionRcpp_InitializeSimulation", (DL_FUNC) &_IntrogressionRcpp_InitializeSimulation, 11},
    {"_IntrogressionRcpp_RunSimulation", (DL_FUNC) &_IntrogressionRcpp_RunSimulation, 0},
    {"_IntrogressionRcpp_WriteOutputandCleanup", (DL_FUNC) &_IntrogressionRcpp_WriteOutputandCleanup, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_IntrogressionRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
