# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IntrogressionSimulation <- function(r, nloci, nploidy, ninit0, ninit1, distlocal, scmajor, sclocal, ngen, nrep, rec, k, threads = 0L) {
    .Call('_pkgIntrogression_IntrogressionSimulation', PACKAGE = 'pkgIntrogression', r, nloci, nploidy, ninit0, ninit1, distlocal, scmajor, sclocal, ngen, nrep, rec, k, threads)
}

