# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppIntrogressionSimulation <- function(parslist, setthreads = 0L, progressbar = FALSE) {
    .Call('_pkgIntrogressionv2_RcppIntrogressionSimulation', PACKAGE = 'pkgIntrogressionv2', parslist, setthreads, progressbar)
}

ShinyInitializeSimulation <- function(parslist) {
    invisible(.Call('_pkgIntrogressionv2_ShinyInitializeSimulation', PACKAGE = 'pkgIntrogressionv2', parslist))
}

ShinyRunSimulation <- function() {
    invisible(.Call('_pkgIntrogressionv2_ShinyRunSimulation', PACKAGE = 'pkgIntrogressionv2'))
}

ShinyWriteOutputandCleanup <- function() {
    .Call('_pkgIntrogressionv2_ShinyWriteOutputandCleanup', PACKAGE = 'pkgIntrogressionv2')
}

