// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// IntrogressionSimulation
Rcpp::List IntrogressionSimulation(double r, int nloci, int nploidy, int ninit0, int ninit1, int distlocal, double scmajor, double sclocal, int ngen, int nrep, double rec, int k, int threads);
RcppExport SEXP _pkgIntrogression_IntrogressionSimulation(SEXP rSEXP, SEXP nlociSEXP, SEXP nploidySEXP, SEXP ninit0SEXP, SEXP ninit1SEXP, SEXP distlocalSEXP, SEXP scmajorSEXP, SEXP sclocalSEXP, SEXP ngenSEXP, SEXP nrepSEXP, SEXP recSEXP, SEXP kSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nloci(nlociSEXP);
    Rcpp::traits::input_parameter< int >::type nploidy(nploidySEXP);
    Rcpp::traits::input_parameter< int >::type ninit0(ninit0SEXP);
    Rcpp::traits::input_parameter< int >::type ninit1(ninit1SEXP);
    Rcpp::traits::input_parameter< int >::type distlocal(distlocalSEXP);
    Rcpp::traits::input_parameter< double >::type scmajor(scmajorSEXP);
    Rcpp::traits::input_parameter< double >::type sclocal(sclocalSEXP);
    Rcpp::traits::input_parameter< int >::type ngen(ngenSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< double >::type rec(recSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(IntrogressionSimulation(r, nloci, nploidy, ninit0, ninit1, distlocal, scmajor, sclocal, ngen, nrep, rec, k, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pkgIntrogression_IntrogressionSimulation", (DL_FUNC) &_pkgIntrogression_IntrogressionSimulation, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_pkgIntrogression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
