// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RcppIntrogressionSimulation
Rcpp::List RcppIntrogressionSimulation(Rcpp::List parslist, int setthreads, bool progressbar);
RcppExport SEXP _pkgIntrogression_RcppIntrogressionSimulation(SEXP parslistSEXP, SEXP setthreadsSEXP, SEXP progressbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type parslist(parslistSEXP);
    Rcpp::traits::input_parameter< int >::type setthreads(setthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type progressbar(progressbarSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppIntrogressionSimulation(parslist, setthreads, progressbar));
    return rcpp_result_gen;
END_RCPP
}
// ShinyInitializeSimulation
void ShinyInitializeSimulation(const Rcpp::List& parslist);
RcppExport SEXP _pkgIntrogression_ShinyInitializeSimulation(SEXP parslistSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parslist(parslistSEXP);
    ShinyInitializeSimulation(parslist);
    return R_NilValue;
END_RCPP
}
// ShinyRunSimulation
void ShinyRunSimulation();
RcppExport SEXP _pkgIntrogression_ShinyRunSimulation() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    ShinyRunSimulation();
    return R_NilValue;
END_RCPP
}
// ShinyWriteOutputandCleanup
Rcpp::List ShinyWriteOutputandCleanup();
RcppExport SEXP _pkgIntrogression_ShinyWriteOutputandCleanup() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ShinyWriteOutputandCleanup());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pkgIntrogression_RcppIntrogressionSimulation", (DL_FUNC) &_pkgIntrogression_RcppIntrogressionSimulation, 3},
    {"_pkgIntrogression_ShinyInitializeSimulation", (DL_FUNC) &_pkgIntrogression_ShinyInitializeSimulation, 1},
    {"_pkgIntrogression_ShinyRunSimulation", (DL_FUNC) &_pkgIntrogression_ShinyRunSimulation, 0},
    {"_pkgIntrogression_ShinyWriteOutputandCleanup", (DL_FUNC) &_pkgIntrogression_ShinyWriteOutputandCleanup, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_pkgIntrogression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
