# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

InitializeSimulation <- function(r, nloci, nploidy, ninit0, ninit1, distlocal, scmajor, sclocal, ngen, rec, k) {
    invisible(.Call('_IntrogressionRcpp_InitializeSimulation', PACKAGE = 'IntrogressionRcpp', r, nloci, nploidy, ninit0, ninit1, distlocal, scmajor, sclocal, ngen, rec, k))
}

RunSimulation <- function() {
    invisible(.Call('_IntrogressionRcpp_RunSimulation', PACKAGE = 'IntrogressionRcpp'))
}

WriteOutputandCleanup <- function() {
    .Call('_IntrogressionRcpp_WriteOutputandCleanup', PACKAGE = 'IntrogressionRcpp')
}

